commands = [
    '<SET ID="ENABLE_SEND_COUNTER" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_TIME" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_CURSOR" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_TIME_TICK" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_PUPIL_LEFT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_PUPIL_RIGHT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_PUPILMM" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_EYE_LEFT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_EYE_RIGHT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_PIX" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_FIX" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_LEFT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_RIGHT" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_BEST" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_POG_AAC" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_CURSOR" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_BLINK" STATE="1" />\r\n',
    '<SET ID="ENABLE_SEND_USER_DATA" STATE="1" />\r\n',
]


TICK_FREQ_COMMAND = '<GET ID="TIME_TICK_FREQUENCY" />\r\n'
START_COMMAND = '<SET ID="ENABLE_SEND_DATA" STATE="1" />\r\n'